image: hseeberger/scala-sbt:11.0.9.1_1.4.6_2.13.4

stages:
  - compile
  - test

compile:
  stage: compile
  script: sbt compile
  needs: []

frontendTest:
  stage: test
  script:
    - sbt "testOnly Parser*"
    - sbt "testOnly Semantic*"
  needs: []
  artifacts:
    when: always
    reports:
      junit:
        - target/test-reports/TEST-*.xml 

backendTest:
  stage: test
  script:
    - sbt assembly
    - apt-get install gcc-arm-linux-gnueabi qemu qemu-user -y
    - sbt "testOnly Backend*"
  needs: []
  artifacts:
    when: always
    reports:
      junit:
        - target/test-reports/TEST-*.xml 
