image: hseeberger/scala-sbt:11.0.9.1_1.4.6_2.13.4

stages:
  - compile
  - test

compile:
  stage: compile
  script: sbt compile
  needs: []

test:
  stage: test
  script: sbt test
  needs: []
  artifacts:
    when: always
    reports:
      junit:
        - target/test-reports/TEST-*.xml 

backend-test:
  stage: test
  script:
    - apt-get install python3 gcc-arm-linux-gnueabi qemu qemu-user python3-pip -y
    - pip3 install colorama
    - python3 backend_test.py
  needs: []
